import { setTimeout as sleep } from "node:timers/promises";
import fs from "node:fs";
import mysql from "mysql2/promise";
import type { Env } from "./config.js";

export interface ChunkRecord {
  id: string;
  text: string;
  source: string;
  path: string;
  title?: string;
  chunkIndex: number;
  url?: string;
}

export interface SyncStateItem {
  hash: string;
  chunkCount: number;
  isConfidential?: boolean;
}

export interface SyncState {
  lastCommit?: string;
  files: Record<string, SyncStateItem>;
}

export const TIDB_AUTO_EMBEDDING_MODEL = "tidbcloud_free/amazon/titan-embed-text-v2";
export const TIDB_AUTO_EMBEDDING_DIMENSION = 1024;

export function resolveSslOptions(env: Env): mysql.SslOptions | undefined {
  if (env.TIDB_SSL === false) {
    return undefined;
  }

  const ssl: mysql.SslOptions = {
    minVersion: "TLSv1.2",
    rejectUnauthorized: env.TIDB_SSL_REJECT_UNAUTHORIZED !== false
  };

  if (env.TIDB_CA) {
    if (env.TIDB_CA.includes("-----BEGIN CERTIFICATE-----")) {
      ssl.ca = env.TIDB_CA;
    } else {
      try {
        if (fs.existsSync(env.TIDB_CA)) {
          ssl.ca = fs.readFileSync(env.TIDB_CA, "utf-8");
        } else {
          ssl.ca = env.TIDB_CA;
        }
      } catch {
        ssl.ca = env.TIDB_CA;
      }
    }
  }

  return ssl;
}

export class TiDBClient {
  private pool: mysql.Pool;

  constructor(env: Env) {
    const dbUrl = env.TIDB_DATABASE_URL || env.DATABASE_URL;
    const ssl = resolveSslOptions(env);

    if (dbUrl) {
      this.pool = mysql.createPool({
        uri: dbUrl,
        ssl,
        waitForConnections: true,
        connectionLimit: 10,
        queueLimit: 0,
        enableKeepAlive: true,
        keepAliveInitialDelay: 10000
      });
    } else {
      this.pool = mysql.createPool({
        host: env.TIDB_HOST,
        port: env.TIDB_PORT || 4000,
        user: env.TIDB_USER,
        password: env.TIDB_PASSWORD,
        database: env.TIDB_DATABASE || "test",
        ssl,
        waitForConnections: true,
        connectionLimit: 10,
        queueLimit: 0,
        enableKeepAlive: true,
        keepAliveInitialDelay: 10000
      });
    }
  }

  async initSchema(): Promise<void> {
    try {
      const [columns] = await this.pool.query<mysql.RowDataPacket[]>(`
        SELECT COLUMN_NAME, EXTRA, GENERATION_EXPRESSION
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'chunks' AND COLUMN_NAME = 'embedding'
      `);

      if (columns.length > 0) {
        const extra = String(columns[0].EXTRA || "");
        const expr = String(columns[0].GENERATION_EXPRESSION || "");
        const isAutoGenerated = extra.includes("GENERATED") || expr.includes("EMBED_TEXT");

        if (!isAutoGenerated) {
          await this.pool.query("DROP TABLE IF EXISTS chunks");
        }
      }
    } catch {
      // Proceed to CREATE TABLE IF NOT EXISTS if inspection fails
    }

    await this.pool.query(`
      CREATE TABLE IF NOT EXISTS chunks (
        id VARCHAR(255) PRIMARY KEY,
        text MEDIUMTEXT NOT NULL,
        source VARCHAR(128) NOT NULL,
        path VARCHAR(512) NOT NULL,
        title VARCHAR(255),
        chunk_index INT NOT NULL DEFAULT 0,
        url VARCHAR(1024),
        embedding VECTOR(${TIDB_AUTO_EMBEDDING_DIMENSION}) GENERATED ALWAYS AS (
          EMBED_TEXT("${TIDB_AUTO_EMBEDDING_MODEL}", text)
        ) STORED,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_source (source),
        INDEX idx_path (path)
      );
    `);

    await this.pool.query(`
      CREATE TABLE IF NOT EXISTS sync_state (
        source VARCHAR(128) PRIMARY KEY,
        state JSON NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      );
    `);
  }

  async getSyncState(source: string): Promise<SyncState | null> {
    const [rows] = await this.pool.query<mysql.RowDataPacket[]>(
      "SELECT state FROM sync_state WHERE source = ?",
      [source]
    );

    if (rows.length === 0 || !rows[0].state) {
      return null;
    }

    const raw = rows[0].state;
    return typeof raw === "string" ? JSON.parse(raw) : (raw as SyncState);
  }

  async saveSyncState(source: string, state: SyncState): Promise<void> {
    const jsonState = JSON.stringify(state);
    await this.pool.query(
      `INSERT INTO sync_state (source, state)
       VALUES (?, ?)
       ON DUPLICATE KEY UPDATE state = VALUES(state), updated_at = CURRENT_TIMESTAMP`,
      [source, jsonState]
    );
  }

  async upsertChunks(chunks: ChunkRecord[]): Promise<number> {
    if (chunks.length === 0) return 0;

    const batchSize = 10;
    let totalUpserted = 0;

    for (let i = 0; i < chunks.length; i += batchSize) {
      const batch = chunks.slice(i, i + batchSize);
      const count = await this.insertBatchWithRetry(batch);
      totalUpserted += count;
    }

    return totalUpserted;
  }

  private async insertBatchWithRetry(batch: ChunkRecord[]): Promise<number> {
    const validBatch = batch.filter((item) => item.text && item.text.replace(/\0/g, "").trim().length > 0);
    if (validBatch.length === 0) return 0;

    let attempts = 0;
    const maxAttempts = 5;

    while (attempts < maxAttempts) {
      attempts++;
      try {
        const valuesPlaceholders: string[] = [];
        const queryParams: unknown[] = [];

        for (const item of validBatch) {
          const cleaned = item.text.replace(/\0/g, "").trim();
          const safeText = cleaned.length > 2500 ? cleaned.slice(0, 2500) : cleaned;

          valuesPlaceholders.push("(?, ?, ?, ?, ?, ?, ?)");
          queryParams.push(
            item.id,
            safeText,
            item.source,
            item.path,
            item.title ?? null,
            item.chunkIndex,
            item.url ?? null
          );
        }

        const sql = `
          INSERT INTO chunks (id, text, source, path, title, chunk_index, url)
          VALUES ${valuesPlaceholders.join(", ")}
          ON DUPLICATE KEY UPDATE
            text = VALUES(text),
            source = VALUES(source),
            path = VALUES(path),
            title = VALUES(title),
            chunk_index = VALUES(chunk_index),
            url = VALUES(url),
            updated_at = CURRENT_TIMESTAMP
        `;

        await this.pool.query(sql, queryParams);
        return validBatch.length;
      } catch (err) {
        const errMsg = String(err);
        const isTransient =
          errMsg.includes("Bedrock") ||
          errMsg.includes("Too Many Requests") ||
          errMsg.includes("rate") ||
          errMsg.includes("503") ||
          errMsg.includes("timeout") ||
          errMsg.includes("deadlock");

        if (isTransient && attempts < maxAttempts) {
          const delayMs = attempts * 1500 + Math.floor(Math.random() * 500);
          await sleep(delayMs);
          continue;
        }

        // Fallback to single-item insertion if batch had multiple items
        if (validBatch.length > 1) {
          let singleUpserted = 0;
          for (const item of validBatch) {
            singleUpserted += await this.insertBatchWithRetry([item]);
          }
          return singleUpserted;
        }

        // If a single row fails persistently, log and skip rather than crashing the entire sync
        console.warn(`[WARN] Skipping chunk ${validBatch[0]?.id} due to persistent error: ${errMsg}`);
        return 0;
      }
    }

    return 0;
  }

  async deleteChunksByIds(ids: string[]): Promise<number> {
    if (ids.length === 0) return 0;

    const batchSize = 100;
    let totalDeleted = 0;

    for (let i = 0; i < ids.length; i += batchSize) {
      const batch = ids.slice(i, i + batchSize);
      const placeholders = batch.map(() => "?").join(", ");
      const [result] = await this.pool.query<mysql.ResultSetHeader>(
        `DELETE FROM chunks WHERE id IN (${placeholders})`,
        batch
      );
      totalDeleted += result.affectedRows;
    }

    return totalDeleted;
  }

  async deleteChunksByPath(source: string, path: string): Promise<number> {
    const [result] = await this.pool.query<mysql.ResultSetHeader>(
      "DELETE FROM chunks WHERE source = ? AND path = ?",
      [source, path]
    );
    return result.affectedRows;
  }

  async clearSourceData(source: string): Promise<{ deletedChunks: number; deletedState: boolean }> {
    const [chunkResult] = await this.pool.query<mysql.ResultSetHeader>(
      "DELETE FROM chunks WHERE source = ?",
      [source]
    );
    const [stateResult] = await this.pool.query<mysql.ResultSetHeader>(
      "DELETE FROM sync_state WHERE source = ?",
      [source]
    );

    return {
      deletedChunks: chunkResult.affectedRows,
      deletedState: stateResult.affectedRows > 0
    };
  }

  async clearAllData(): Promise<{ deletedChunks: number; deletedState: boolean }> {
    const [chunkResult] = await this.pool.query<mysql.ResultSetHeader>("DELETE FROM chunks");
    const [stateResult] = await this.pool.query<mysql.ResultSetHeader>("DELETE FROM sync_state");

    return {
      deletedChunks: chunkResult.affectedRows,
      deletedState: stateResult.affectedRows > 0
    };
  }

  async close(): Promise<void> {
    await this.pool.end();
  }
}
